In [1]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 
print ('First array:' )
print (a)


First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [2]:
print ('Second array:' )
b = np.array([10,10,10]) 
print (b)

Second array:
[10 10 10]


In [3]:
print( 'Add the two arrays:' )
print (np.add(a,b) )
print ('Subtract the two arrays:' )
print (np.subtract(a,b))
print ('Multiply the two arrays:' )
print (np.multiply(a,b) )





Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


In [5]:
print ('Divide the two arrays:')
print (np.divide(a,b))
print('Dot product two arrays:')
print(np.dot(a,b))


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
Dot product two arrays:
[ 30. 120. 210.]


In [6]:
print(np.empty((2,4)))

[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]


In [7]:
print(np.full((2,2), 3)
)

[[3 3]
 [3 3]]
