In [1]:
import numpy as np
ls = [1,2,3,4,5,6]

arr = np.array(ls , dtype='int')
print(arr)

[1 2 3 4 5 6]


In [11]:
# 8bit


ls = [100,3,5,6,256]
arr = np.array(ls, dtype='uint8')
print(arr)

[100   3   5   6   0]


C:\Users\Sansk\AppData\Local\Temp\ipykernel_5476\2129807007.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array(ls, dtype='uint8')


In [10]:

ls = [100,3,5,6,256]
arr = np.array(ls, dtype='uint16')
print(arr)

[100   3   5   6 256]


In [3]:
import numpy as np 
ls = [[4],[1,6]]
arr = np.array(ls, dtype='uint8', ndmin=2)
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [4]:
import numpy as np 
ls = [[2,4],[1,6]]
arr = np.array(ls, dtype='uint8', ndmin=2)
print(arr)

[[2 4]
 [1 6]]


In [21]:
# reversed numpy array

lst = list(map(int,input().split()))

arr = np.flip(lst)

print(arr)

[6 5 4 3 2 1]


In [23]:
import numpy as np

my_list = list(map(int,input().split()))
my_array = np.array(my_list).reshape(3,3)
print(my_array)


[1 2 3 4 5 6 7 8 9]


In [31]:
import numpy as np



elements = list(map(int, input().split()))  
array_3x3 = np.eye(3, 3)   
print(array_3x3)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
lst = list(map(int, input().split()))

In [ ]:
N, M = map(int,input().split())
lst1 = list(map(int, input().split()))
lst2 = list(map(int, input().split()))


