In [ ]:
#matrix
class array:
    def __init__(self,lst):
        self.last = lst 
      

In [1]:
import numpy as np
ls = [1,3,4,5,6]
arr = np.array(ls)
print(arr)

print(f'{arr=}')
print(f'{ls=}')
type(arr)
type(ls)

[1 3 4 5 6]
arr=array([1, 3, 4, 5, 6])
ls=[1, 3, 4, 5, 6]


list

In [2]:
ls = [1,300,4,5,60]
arr = np.array(ls)
print(arr)

[  1 300   4   5  60]


In [11]:
class array :
    def __init__(self, lst):
        self.lst = lst
        
lst = [2,3,45,6,7]
arr = array(lst)
arr
print(arr)
arr.lst
print(str(array(lst)))

In [3]:
class array :
    def __init__(self, lst):
        self.lst = lst
    def __str__(self):
        st = str(self.lst).replace(',','')
        return st
        
lst = [2,3,45,6,7]
arr = array(lst)
print(arr,type)

[2 3 45 6 7] <class 'type'>


In [2]:
class Array:
    def __init__(self, lst, r=0, c=0):
        self.lst = lst
        self.r = r
        self.c = c
        if r != 0 and c != 0:
            self.lst = [lst[i:i + c] for i in range(0, len(lst), c)]

    def __add__(self, other):
        if (self.r, self.c) == (other.r, other.c):
            result = [[0] * self.c for _ in range(self.r)]
            for i in range(self.r):
                for j in range(self.c):
                    result[i][j] = self.lst[i][j] + other.lst[i][j]
            return Array(result)
        else:
            print("Not Compatible for addition, dimensions of both matrices should be equal")

    def __sub__(self, other):
        if (self.r, self.c) == (other.r, other.c):
            result = [[0] * self.c for _ in range(self.r)]
            for i in range(self.r):
                for j in range(self.c):
                    result[i][j] = self.lst[i][j] - other.lst[i][j]
            return Array(result)
        else:
            print("Not Compatible for subtraction, dimensions of both matrices should be equal")

    def __mul__(self, other):
        if self.c == other.r:
            result = [[0] * other.c for _ in range(self.r)]
            for i in range(self.r):
                for j in range(other.c):
                    for k in range(self.c):
                        result[i][j] += self.lst[i][k] * other.lst[k][j]
            return Array(result)
        else:
            print("Not Compatible for multiplication")
            return None 
    def dot(self, other):
        return self.__mul__(other)  # Using the same logic for dot multiplication

    def transpose(self):
        result = [[0] * self.r for _ in range(self.c)]
        for i in range(self.c):
            for j in range(self.r):
                result[i][j] = self.lst[j][i]
        return Array(result)

    def disp_mat(self):
        for row in self.lst:
            print(*row)


# Input matrices
lst1 = list(map(int, input("Enter the elements for matrix 1: \n").split()))
r1, c1 = list(map(int, input("Enter the dimensions for matrix 1: \n").split()))
arr1 = Array(lst1, r1, c1)

lst2 = list(map(int, input("Enter the elements for matrix 2: \n").split()))
r2, c2 = list(map(int, input("Enter the dimensions for matrix 2: \n").split()))
arr2 = Array(lst2, r2, c2)

# Display matrices
print("\nMatrix-1\n")
arr1.disp_mat()

print("\nMatrix-2\n")
arr2.disp_mat()

# Perform operations
out = arr1 + arr2
out1 = arr1 * arr2
out2 = arr1 - arr2
out3 = arr1.dot(arr2)
out4 = arr1.transpose()
out5 = arr2.transpose()

# Display results
print("\nAddition")
out.disp_mat()

print("\nSubtraction")
out2.disp_mat()

print("\nMultiplication")
out1.disp_mat()

print("\nDot Multiplication")
out3.disp_mat()

print("\nTranspose")
out4.disp_mat()
print()

out5.disp_mat()



Matrix-1

1 2 3
4 5 6
7 8 9

Matrix-2

7 8 5
1 2 4
9 6 3

Addition
8 10 8
5 7 10
16 14 12

Subtraction
-6 -6 -2
3 3 2
-2 2 6

Multiplication
36 30 22
87 78 58
138 126 94

Dot Multiplication
36 30 22
87 78 58
138 126 94

Transpose
1 4 7
2 5 8
3 6 9

7 1 9
8 2 6
5 4 3


: 